/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.yuanqingfei.swmm;

public class swmm5JNI {
  public final static native int swmm_run(String jarg1, String jarg2, String jarg3);
  public final static native int swmm_open(String jarg1, String jarg2, String jarg3);
  public final static native int swmm_start(int jarg1);
  public final static native int swmm_step(long jarg1);
  public final static native int swmm_end();
  public final static native int swmm_report();
  public final static native int swmm_getMassBalErr(long jarg1, long jarg2, long jarg3);
  public final static native int swmm_close();
  public final static native int swmm_getVersion();
}
