/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package me.yuanqingfei.swmm;

public class swmm5 {
  public static int swmm_run(String f1, String f2, String f3) {
    return swmm5JNI.swmm_run(f1, f2, f3);
  }

  public static int swmm_open(String f1, String f2, String f3) {
    return swmm5JNI.swmm_open(f1, f2, f3);
  }

  public static int swmm_start(int saveFlag) {
    return swmm5JNI.swmm_start(saveFlag);
  }

  public static int swmm_step(SWIGTYPE_p_double elapsedTime) {
    return swmm5JNI.swmm_step(SWIGTYPE_p_double.getCPtr(elapsedTime));
  }

  public static int swmm_end() {
    return swmm5JNI.swmm_end();
  }

  public static int swmm_report() {
    return swmm5JNI.swmm_report();
  }

  public static int swmm_getMassBalErr(SWIGTYPE_p_float runoffErr, SWIGTYPE_p_float flowErr, SWIGTYPE_p_float qualErr) {
    return swmm5JNI.swmm_getMassBalErr(SWIGTYPE_p_float.getCPtr(runoffErr), SWIGTYPE_p_float.getCPtr(flowErr), SWIGTYPE_p_float.getCPtr(qualErr));
  }

  public static int swmm_close() {
    return swmm5JNI.swmm_close();
  }

  public static int swmm_getVersion() {
    return swmm5JNI.swmm_getVersion();
  }

}
